apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forex-ingress
  namespace: forex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - forex.leanstax.com
      secretName: forex-tls
  rules:
    - host: forex.leanstax.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forex-api
                port:
                  number: 8080
